#!/bin/sh

# Ensure node/npm/npx are in PATH
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
export PATH="/usr/local/bin:/opt/homebrew/bin:$HOME/.nvm/versions/node/$(node -v 2>/dev/null)/bin:$PATH" 2>/dev/null

npx --no -- commitlint --edit "$1"
